--- 
language: node_js
node_js: 
- 0.8
env:
  global:
    secure: |-
      cSJmFUQiOuqrtPB/5/8vAmpv35W85mcu8UVyEDHfW1dOlwf7BlsxvXbLgcSSc3u0EgFXeW8c0EEIOUk7hCaw8Va6FhWdfnPx9P0xLDY/OzHEhi/ZvL83KPW+p9N9RDIXCgFfEmPS8bO1Gy0LsF9cQByXwGXQ5XF8u5H1hF/aAIw=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm link
- npm install -g grunt-cli

# Saucelabs only allows two concurrent browsers, so we do two seperate grunt
# tasks, each with two of the browsers running
script:
- grunt install
- grunt
- grunt karma:sauce1
- grunt karma:sauce2

after_success: ./build/update-gh-pages.sh

